version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
    volumes:
      - ./back:/app
    working_dir: /app

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001/api/v1
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - backend